version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/mapesa-node-api"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "pip"
    directory: "/mapesa-flask-api"
    schedule:
      interval: "weekly"
